##############################################################################
## This file is part of 'axi-soc-ultra-plus-core'.
## It is subject to the license terms in the LICENSE.txt file found in the
## top-level directory of this distribution and at:
##    https://confluence.slac.stanford.edu/display/ppareg/LICENSE.html.
## No part of 'axi-soc-ultra-plus-core', including this file,
## may be copied, modified, propagated, or distributed except according to
## the terms contained in the LICENSE.txt file.
##############################################################################

set_property BITSTREAM.CONFIG.OVERTEMPSHUTDOWN ENABLE [current_design]

set_property -dict { PACKAGE_PIN W17 IOSTANDARD ANALOG } [get_ports { vPIn }]
set_property -dict { PACKAGE_PIN Y16 IOSTANDARD ANALOG } [get_ports { vNIn }]

##############################################################################

set_property -dict { PACKAGE_PIN AF16 IOSTANDARD LVCMOS18 } [get_ports { pmod[0][0] }]
set_property -dict { PACKAGE_PIN AG17 IOSTANDARD LVCMOS18 } [get_ports { pmod[0][1] }]
set_property -dict { PACKAGE_PIN AJ16 IOSTANDARD LVCMOS18 } [get_ports { pmod[0][2] }]
set_property -dict { PACKAGE_PIN AK17 IOSTANDARD LVCMOS18 } [get_ports { pmod[0][3] }]
set_property -dict { PACKAGE_PIN AF15 IOSTANDARD LVCMOS18 } [get_ports { pmod[0][4] }]
set_property -dict { PACKAGE_PIN AF17 IOSTANDARD LVCMOS18 } [get_ports { pmod[0][5] }]
set_property -dict { PACKAGE_PIN AH17 IOSTANDARD LVCMOS18 } [get_ports { pmod[0][6] }]
set_property -dict { PACKAGE_PIN AK16 IOSTANDARD LVCMOS18 } [get_ports { pmod[0][7] }]

set_property -dict { PACKAGE_PIN AW13 IOSTANDARD LVCMOS18 } [get_ports { pmod[1][0] }]
set_property -dict { PACKAGE_PIN AR13 IOSTANDARD LVCMOS18 } [get_ports { pmod[1][1] }]
set_property -dict { PACKAGE_PIN AU13 IOSTANDARD LVCMOS18 } [get_ports { pmod[1][2] }]
set_property -dict { PACKAGE_PIN AV13 IOSTANDARD LVCMOS18 } [get_ports { pmod[1][3] }]
set_property -dict { PACKAGE_PIN AU15 IOSTANDARD LVCMOS18 } [get_ports { pmod[1][4] }]
set_property -dict { PACKAGE_PIN AP14 IOSTANDARD LVCMOS18 } [get_ports { pmod[1][5] }]
set_property -dict { PACKAGE_PIN AT15 IOSTANDARD LVCMOS18 } [get_ports { pmod[1][6] }]
set_property -dict { PACKAGE_PIN AU14 IOSTANDARD LVCMOS18 } [get_ports { pmod[1][7] }]

set_property -dict { PACKAGE_PIN AW16 IOSTANDARD LVCMOS18 } [get_ports { pmod[2][0] }]
set_property -dict { PACKAGE_PIN AW15 IOSTANDARD LVCMOS18 } [get_ports { pmod[2][1] }]
set_property -dict { PACKAGE_PIN AW14 IOSTANDARD LVCMOS18 } [get_ports { pmod[2][2] }]
set_property -dict { PACKAGE_PIN AR16 IOSTANDARD LVCMOS18 } [get_ports { pmod[2][3] }]
set_property -dict { PACKAGE_PIN AV16 IOSTANDARD LVCMOS18 } [get_ports { pmod[2][4] }]
set_property -dict { PACKAGE_PIN AT16 IOSTANDARD LVCMOS18 } [get_ports { pmod[2][5] }]
#set_property -dict { PACKAGE_PIN XXXX IOSTANDARD LVCMOS18 } [get_ports { pmod[2][6] }]; # Not implemented on RFSoC 4x2
#set_property -dict { PACKAGE_PIN XXXX IOSTANDARD LVCMOS18 } [get_ports { pmod[2][7] }]; # Not implemented on RFSoC 4x2

set_property -dict { PACKAGE_PIN AK13 IOSTANDARD LVCMOS18 } [get_ports { irigAdcSdo  }]
set_property -dict { PACKAGE_PIN AH12 IOSTANDARD LVCMOS18 } [get_ports { irigAdcSclk }]
set_property -dict { PACKAGE_PIN AH13 IOSTANDARD LVCMOS18 } [get_ports { irigTrigOut }]
set_property -dict { PACKAGE_PIN AJ13 IOSTANDARD LVCMOS18 } [get_ports { irigCompOut }]
set_property -dict { PACKAGE_PIN AG14 IOSTANDARD LVCMOS18 } [get_ports { irigAdcCsL  }]

##############################################################################

set_property -dict { PACKAGE_PIN AN11 IOSTANDARD LVDS } [get_ports { plClkP }]
set_property -dict { PACKAGE_PIN AP11 IOSTANDARD LVDS } [get_ports { plClkN }]

set_property -dict { PACKAGE_PIN AP18 IOSTANDARD LVDS } [get_ports { plSysRefP }]
set_property -dict { PACKAGE_PIN AR18 IOSTANDARD LVDS } [get_ports { plSysRefN }]

set_property -dict { PACKAGE_PIN AR11 IOSTANDARD LVCMOS18 } [get_ports { userLed[0] }]
set_property -dict { PACKAGE_PIN AW10 IOSTANDARD LVCMOS18 } [get_ports { userLed[1] }]
set_property -dict { PACKAGE_PIN AT11 IOSTANDARD LVCMOS18 } [get_ports { userLed[2] }]
set_property -dict { PACKAGE_PIN AU10 IOSTANDARD LVCMOS18 } [get_ports { userLed[3] }]

##############################################################################

## ADC TILE 224
#set_property PACKAGE_PIN AP2 [get_ports { adcP[0] }]
#set_property PACKAGE_PIN AP1 [get_ports { adcN[0] }]
#set_property PACKAGE_PIN AM2 [get_ports { adcP[1] }]
#set_property PACKAGE_PIN AM1 [get_ports { adcN[1] }]
#set_property PACKAGE_PIN AF5 [get_ports { adcClkP[0] }]
#set_property PACKAGE_PIN AF4 [get_ports { adcClkN[0] }]

## ADC TILE 226
#set_property PACKAGE_PIN AF2 [get_ports { adcP[2] }]
#set_property PACKAGE_PIN AF1 [get_ports { adcN[2] }]
#set_property PACKAGE_PIN AD2 [get_ports { adcP[3] }]
#set_property PACKAGE_PIN AD1 [get_ports { adcN[3] }]
#set_property PACKAGE_PIN AB5 [get_ports { adcClkP[1] }]
#set_property PACKAGE_PIN AB4 [get_ports { adcClkN[1] }]

## DAC TILE 228
#set_property PACKAGE_PIN U2 [get_ports { dacP[0] }]
#set_property PACKAGE_PIN U1 [get_ports { dacN[0] }]
#set_property PACKAGE_PIN R5 [get_ports { dacClkP[0] }]
#set_property PACKAGE_PIN R4 [get_ports { dacClkN[0] }]
#set_property PACKAGE_PIN U5 [get_ports { sysRefP }]
#set_property PACKAGE_PIN U4 [get_ports { sysRefN }]

## DAC TILE 230
#set_property PACKAGE_PIN J2 [get_ports { dacP[1] }]
#set_property PACKAGE_PIN J1 [get_ports { dacN[1] }]
#set_property PACKAGE_PIN N5 [get_ports { dacClkP[1] }]
#set_property PACKAGE_PIN N4 [get_ports { dacClkN[1] }]

##############################################################################

set_property PACKAGE_PIN J15 [get_ports {ddrDm[0]}]
set_property PACKAGE_PIN N14 [get_ports {ddrDm[1]}]
set_property PACKAGE_PIN D18 [get_ports {ddrDm[2]}]
set_property PACKAGE_PIN G17 [get_ports {ddrDm[3]}]
set_property PACKAGE_PIN F21 [get_ports {ddrDm[4]}]
set_property PACKAGE_PIN J23 [get_ports {ddrDm[5]}]
set_property PACKAGE_PIN C23 [get_ports {ddrDm[6]}]
set_property PACKAGE_PIN N20 [get_ports {ddrDm[7]}]
set_property PACKAGE_PIN L19 [get_ports {ddrDq[63]}]
set_property PACKAGE_PIN L23 [get_ports {ddrDq[62]}]
set_property PACKAGE_PIN M19 [get_ports {ddrDq[61]}]
set_property PACKAGE_PIN N19 [get_ports {ddrDq[60]}]
set_property PACKAGE_PIN L21 [get_ports {ddrDq[59]}]
set_property PACKAGE_PIN L22 [get_ports {ddrDq[58]}]
set_property PACKAGE_PIN L20 [get_ports {ddrDq[57]}]
set_property PACKAGE_PIN M20 [get_ports {ddrDq[56]}]
set_property PACKAGE_PIN B20 [get_ports {ddrDq[55]}]
set_property PACKAGE_PIN C20 [get_ports {ddrDq[54]}]
set_property PACKAGE_PIN A21 [get_ports {ddrDq[53]}]
set_property PACKAGE_PIN C22 [get_ports {ddrDq[52]}]
set_property PACKAGE_PIN A20 [get_ports {ddrDq[51]}]
set_property PACKAGE_PIN B24 [get_ports {ddrDq[50]}]
set_property PACKAGE_PIN A24 [get_ports {ddrDq[49]}]
set_property PACKAGE_PIN C21 [get_ports {ddrDq[48]}]
set_property PACKAGE_PIN H21 [get_ports {ddrDq[47]}]
set_property PACKAGE_PIN H23 [get_ports {ddrDq[46]}]
set_property PACKAGE_PIN H22 [get_ports {ddrDq[45]}]
set_property PACKAGE_PIN L24 [get_ports {ddrDq[44]}]
set_property PACKAGE_PIN G23 [get_ports {ddrDq[43]}]
set_property PACKAGE_PIN K24 [get_ports {ddrDq[42]}]
set_property PACKAGE_PIN G22 [get_ports {ddrDq[41]}]
set_property PACKAGE_PIN J21 [get_ports {ddrDq[40]}]
set_property PACKAGE_PIN G20 [get_ports {ddrDq[39]}]
set_property PACKAGE_PIN F24 [get_ports {ddrDq[38]}]
set_property PACKAGE_PIN F20 [get_ports {ddrDq[37]}]
set_property PACKAGE_PIN E23 [get_ports {ddrDq[36]}]
set_property PACKAGE_PIN E21 [get_ports {ddrDq[35]}]
set_property PACKAGE_PIN E22 [get_ports {ddrDq[34]}]
set_property PACKAGE_PIN D21 [get_ports {ddrDq[33]}]
set_property PACKAGE_PIN E24 [get_ports {ddrDq[32]}]
set_property PACKAGE_PIN F15 [get_ports {ddrDq[31]}]
set_property PACKAGE_PIN E18 [get_ports {ddrDq[30]}]
set_property PACKAGE_PIN E17 [get_ports {ddrDq[29]}]
set_property PACKAGE_PIN H18 [get_ports {ddrDq[28]}]
set_property PACKAGE_PIN G15 [get_ports {ddrDq[27]}]
set_property PACKAGE_PIN F16 [get_ports {ddrDq[26]}]
set_property PACKAGE_PIN E16 [get_ports {ddrDq[25]}]
set_property PACKAGE_PIN G18 [get_ports {ddrDq[24]}]
set_property PACKAGE_PIN A16 [get_ports {ddrDq[23]}]
set_property PACKAGE_PIN B19 [get_ports {ddrDq[22]}]
set_property PACKAGE_PIN C16 [get_ports {ddrDq[21]}]
set_property PACKAGE_PIN D15 [get_ports {ddrDq[20]}]
set_property PACKAGE_PIN A19 [get_ports {ddrDq[19]}]
set_property PACKAGE_PIN C17 [get_ports {ddrDq[18]}]
set_property PACKAGE_PIN A17 [get_ports {ddrDq[17]}]
set_property PACKAGE_PIN D16 [get_ports {ddrDq[16]}]
set_property PACKAGE_PIN M12 [get_ports {ddrDq[15]}]
set_property PACKAGE_PIN M15 [get_ports {ddrDq[14]}]
set_property PACKAGE_PIN M13 [get_ports {ddrDq[13]}]
set_property PACKAGE_PIN M17 [get_ports {ddrDq[12]}]
set_property PACKAGE_PIN L12 [get_ports {ddrDq[11]}]
set_property PACKAGE_PIN N15 [get_ports {ddrDq[10]}]
set_property PACKAGE_PIN N13 [get_ports {ddrDq[9]}]
set_property PACKAGE_PIN N17 [get_ports {ddrDq[8]}]
set_property PACKAGE_PIN L17 [get_ports {ddrDq[7]}]
set_property PACKAGE_PIN J19 [get_ports {ddrDq[6]}]
set_property PACKAGE_PIN K16 [get_ports {ddrDq[5]}]
set_property PACKAGE_PIN J18 [get_ports {ddrDq[4]}]
set_property PACKAGE_PIN H16 [get_ports {ddrDq[3]}]
set_property PACKAGE_PIN H17 [get_ports {ddrDq[2]}]
set_property PACKAGE_PIN J16 [get_ports {ddrDq[1]}]
set_property PACKAGE_PIN K17 [get_ports {ddrDq[0]}]
set_property PACKAGE_PIN K19 [get_ports {ddrDqsP[0]}]
set_property PACKAGE_PIN K18 [get_ports {ddrDqsN[0]}]
set_property PACKAGE_PIN L15 [get_ports {ddrDqsP[1]}]
set_property PACKAGE_PIN L14 [get_ports {ddrDqsN[1]}]
set_property PACKAGE_PIN B18 [get_ports {ddrDqsP[2]}]
set_property PACKAGE_PIN B17 [get_ports {ddrDqsN[2]}]
set_property PACKAGE_PIN G19 [get_ports {ddrDqsP[3]}]
set_property PACKAGE_PIN F19 [get_ports {ddrDqsN[3]}]
set_property PACKAGE_PIN D23 [get_ports {ddrDqsP[4]}]
set_property PACKAGE_PIN D24 [get_ports {ddrDqsN[4]}]
set_property PACKAGE_PIN J20 [get_ports {ddrDqsP[5]}]
set_property PACKAGE_PIN H20 [get_ports {ddrDqsN[5]}]
set_property PACKAGE_PIN B22 [get_ports {ddrDqsP[6]}]
set_property PACKAGE_PIN A22 [get_ports {ddrDqsN[6]}]
set_property PACKAGE_PIN K21 [get_ports {ddrDqsP[7]}]
set_property PACKAGE_PIN K22 [get_ports {ddrDqsN[7]}]
set_property PACKAGE_PIN E13 [get_ports {ddrA[16]}]
set_property PACKAGE_PIN F14 [get_ports {ddrA[15]}]
set_property PACKAGE_PIN K13 [get_ports {ddrA[14]}]
set_property PACKAGE_PIN H11 [get_ports {ddrA[13]}]
set_property PACKAGE_PIN D13 [get_ports {ddrA[12]}]
set_property PACKAGE_PIN G7 [get_ports {ddrA[11]}]
set_property PACKAGE_PIN C15 [get_ports {ddrA[10]}]
set_property PACKAGE_PIN H6 [get_ports {ddrA[9]}]
set_property PACKAGE_PIN A11 [get_ports {ddrA[8]}]
set_property PACKAGE_PIN H13 [get_ports {ddrA[7]}]
set_property PACKAGE_PIN J7 [get_ports {ddrA[6]}]
set_property PACKAGE_PIN F11 [get_ports {ddrA[5]}]
set_property PACKAGE_PIN D14 [get_ports {ddrA[4]}]
set_property PACKAGE_PIN F10 [get_ports {ddrA[3]}]
set_property PACKAGE_PIN A14 [get_ports {ddrA[2]}]
set_property PACKAGE_PIN G6 [get_ports {ddrA[1]}]
set_property PACKAGE_PIN B13 [get_ports {ddrA[0]}]
set_property PACKAGE_PIN A12 [get_ports {ddrBa[0]}]
set_property PACKAGE_PIN H10 [get_ports {ddrBa[1]}]
set_property PACKAGE_PIN H12 [get_ports {ddrBg[0]}]
set_property PACKAGE_PIN E11 [get_ports {ddrCsL[0]}]
set_property PACKAGE_PIN B14 [get_ports ddrActL]
set_property PACKAGE_PIN F12 [get_ports {ddrCke[0]}]
set_property PACKAGE_PIN A15 [get_ports {ddrOdt[0]}]
set_property PACKAGE_PIN E14 [get_ports ddrRstL]
set_property PACKAGE_PIN J11 [get_ports {ddrCkP[0]}]
set_property PACKAGE_PIN J10 [get_ports {ddrCkN[0]}]
set_property PACKAGE_PIN G13 [get_ports ddrClkP]
set_property PACKAGE_PIN G12 [get_ports ddrClkN]

set_property DRIVE 8 [get_ports ddrRstL]
set_property SLEW FAST [get_ports ddrActL]
set_property SLEW FAST [get_ports {ddrDq[63]}]
set_property SLEW FAST [get_ports {ddrDq[62]}]
set_property SLEW FAST [get_ports {ddrDq[61]}]
set_property SLEW FAST [get_ports {ddrDq[60]}]
set_property SLEW FAST [get_ports {ddrDq[59]}]
set_property SLEW FAST [get_ports {ddrDq[58]}]
set_property SLEW FAST [get_ports {ddrDq[57]}]
set_property SLEW FAST [get_ports {ddrDq[56]}]
set_property SLEW FAST [get_ports {ddrDq[55]}]
set_property SLEW FAST [get_ports {ddrDq[54]}]
set_property SLEW FAST [get_ports {ddrDq[53]}]
set_property SLEW FAST [get_ports {ddrDq[52]}]
set_property SLEW FAST [get_ports {ddrDq[51]}]
set_property SLEW FAST [get_ports {ddrDq[50]}]
set_property SLEW FAST [get_ports {ddrDq[49]}]
set_property SLEW FAST [get_ports {ddrDq[48]}]
set_property SLEW FAST [get_ports {ddrDq[47]}]
set_property SLEW FAST [get_ports {ddrDq[46]}]
set_property SLEW FAST [get_ports {ddrDq[45]}]
set_property SLEW FAST [get_ports {ddrDq[44]}]
set_property SLEW FAST [get_ports {ddrDq[43]}]
set_property SLEW FAST [get_ports {ddrDq[42]}]
set_property SLEW FAST [get_ports {ddrDq[41]}]
set_property SLEW FAST [get_ports {ddrDq[40]}]
set_property SLEW FAST [get_ports {ddrDq[39]}]
set_property SLEW FAST [get_ports {ddrDq[38]}]
set_property SLEW FAST [get_ports {ddrDq[37]}]
set_property SLEW FAST [get_ports {ddrDq[36]}]
set_property SLEW FAST [get_ports {ddrDq[35]}]
set_property SLEW FAST [get_ports {ddrDq[34]}]
set_property SLEW FAST [get_ports {ddrDq[33]}]
set_property SLEW FAST [get_ports {ddrDq[32]}]
set_property SLEW FAST [get_ports {ddrDq[31]}]
set_property SLEW FAST [get_ports {ddrDq[30]}]
set_property SLEW FAST [get_ports {ddrDq[29]}]
set_property SLEW FAST [get_ports {ddrDq[28]}]
set_property SLEW FAST [get_ports {ddrDq[27]}]
set_property SLEW FAST [get_ports {ddrDq[26]}]
set_property SLEW FAST [get_ports {ddrDq[25]}]
set_property SLEW FAST [get_ports {ddrDq[24]}]
set_property SLEW FAST [get_ports {ddrDq[23]}]
set_property SLEW FAST [get_ports {ddrDq[22]}]
set_property SLEW FAST [get_ports {ddrDq[21]}]
set_property SLEW FAST [get_ports {ddrDq[20]}]
set_property SLEW FAST [get_ports {ddrDq[19]}]
set_property SLEW FAST [get_ports {ddrDq[18]}]
set_property SLEW FAST [get_ports {ddrDq[17]}]
set_property SLEW FAST [get_ports {ddrDq[16]}]
set_property SLEW FAST [get_ports {ddrDq[15]}]
set_property SLEW FAST [get_ports {ddrDq[14]}]
set_property SLEW FAST [get_ports {ddrDq[13]}]
set_property SLEW FAST [get_ports {ddrDq[12]}]
set_property SLEW FAST [get_ports {ddrDq[11]}]
set_property SLEW FAST [get_ports {ddrDq[10]}]
set_property SLEW FAST [get_ports {ddrDq[9]}]
set_property SLEW FAST [get_ports {ddrDq[8]}]
set_property SLEW FAST [get_ports {ddrDq[7]}]
set_property SLEW FAST [get_ports {ddrDq[6]}]
set_property SLEW FAST [get_ports {ddrDq[5]}]
set_property SLEW FAST [get_ports {ddrDq[4]}]
set_property SLEW FAST [get_ports {ddrDq[3]}]
set_property SLEW FAST [get_ports {ddrDq[2]}]
set_property SLEW FAST [get_ports {ddrDq[1]}]
set_property SLEW FAST [get_ports {ddrDq[0]}]
set_property SLEW FAST [get_ports {ddrDqsN[7]}]
set_property SLEW FAST [get_ports {ddrDqsN[6]}]
set_property SLEW FAST [get_ports {ddrDqsN[5]}]
set_property SLEW FAST [get_ports {ddrDqsN[4]}]
set_property SLEW FAST [get_ports {ddrDqsN[3]}]
set_property SLEW FAST [get_ports {ddrDqsN[2]}]
set_property SLEW FAST [get_ports {ddrDqsN[1]}]
set_property SLEW FAST [get_ports {ddrDqsN[0]}]
set_property SLEW FAST [get_ports {ddrDqsP[7]}]
set_property SLEW FAST [get_ports {ddrDqsP[6]}]
set_property SLEW FAST [get_ports {ddrDqsP[5]}]
set_property SLEW FAST [get_ports {ddrDqsP[4]}]
set_property SLEW FAST [get_ports {ddrDqsP[3]}]
set_property SLEW FAST [get_ports {ddrDqsP[2]}]
set_property SLEW FAST [get_ports {ddrDqsP[1]}]
set_property SLEW FAST [get_ports {ddrDqsP[0]}]
set_property ODT RTT_60 [get_ports {ddrDq[63]}]
set_property ODT RTT_60 [get_ports {ddrDq[62]}]
set_property ODT RTT_60 [get_ports {ddrDq[61]}]
set_property ODT RTT_60 [get_ports {ddrDq[60]}]
set_property ODT RTT_60 [get_ports {ddrDq[59]}]
set_property ODT RTT_60 [get_ports {ddrDq[58]}]
set_property ODT RTT_60 [get_ports {ddrDq[57]}]
set_property ODT RTT_60 [get_ports {ddrDq[56]}]
set_property ODT RTT_60 [get_ports {ddrDq[55]}]
set_property ODT RTT_60 [get_ports {ddrDq[54]}]
set_property ODT RTT_60 [get_ports {ddrDq[53]}]
set_property ODT RTT_60 [get_ports {ddrDq[52]}]
set_property ODT RTT_60 [get_ports {ddrDq[51]}]
set_property ODT RTT_60 [get_ports {ddrDq[50]}]
set_property ODT RTT_60 [get_ports {ddrDq[49]}]
set_property ODT RTT_60 [get_ports {ddrDq[48]}]
set_property ODT RTT_60 [get_ports {ddrDq[47]}]
set_property ODT RTT_60 [get_ports {ddrDq[46]}]
set_property ODT RTT_60 [get_ports {ddrDq[45]}]
set_property ODT RTT_60 [get_ports {ddrDq[44]}]
set_property ODT RTT_60 [get_ports {ddrDq[43]}]
set_property ODT RTT_60 [get_ports {ddrDq[42]}]
set_property ODT RTT_60 [get_ports {ddrDq[41]}]
set_property ODT RTT_60 [get_ports {ddrDq[40]}]
set_property ODT RTT_60 [get_ports {ddrDq[39]}]
set_property ODT RTT_60 [get_ports {ddrDq[38]}]
set_property ODT RTT_60 [get_ports {ddrDq[37]}]
set_property ODT RTT_60 [get_ports {ddrDq[36]}]
set_property ODT RTT_60 [get_ports {ddrDq[35]}]
set_property ODT RTT_60 [get_ports {ddrDq[34]}]
set_property ODT RTT_60 [get_ports {ddrDq[33]}]
set_property ODT RTT_60 [get_ports {ddrDq[32]}]
set_property ODT RTT_60 [get_ports {ddrDq[31]}]
set_property ODT RTT_60 [get_ports {ddrDq[30]}]
set_property ODT RTT_60 [get_ports {ddrDq[29]}]
set_property ODT RTT_60 [get_ports {ddrDq[28]}]
set_property ODT RTT_60 [get_ports {ddrDq[27]}]
set_property ODT RTT_60 [get_ports {ddrDq[26]}]
set_property ODT RTT_60 [get_ports {ddrDq[25]}]
set_property ODT RTT_60 [get_ports {ddrDq[24]}]
set_property ODT RTT_60 [get_ports {ddrDq[23]}]
set_property ODT RTT_60 [get_ports {ddrDq[22]}]
set_property ODT RTT_60 [get_ports {ddrDq[21]}]
set_property ODT RTT_60 [get_ports {ddrDq[20]}]
set_property ODT RTT_60 [get_ports {ddrDq[19]}]
set_property ODT RTT_60 [get_ports {ddrDq[18]}]
set_property ODT RTT_60 [get_ports {ddrDq[17]}]
set_property ODT RTT_60 [get_ports {ddrDq[16]}]
set_property ODT RTT_60 [get_ports {ddrDq[15]}]
set_property ODT RTT_60 [get_ports {ddrDq[14]}]
set_property ODT RTT_60 [get_ports {ddrDq[13]}]
set_property ODT RTT_60 [get_ports {ddrDq[12]}]
set_property ODT RTT_60 [get_ports {ddrDq[11]}]
set_property ODT RTT_60 [get_ports {ddrDq[10]}]
set_property ODT RTT_60 [get_ports {ddrDq[9]}]
set_property ODT RTT_60 [get_ports {ddrDq[8]}]
set_property ODT RTT_60 [get_ports {ddrDq[7]}]
set_property ODT RTT_60 [get_ports {ddrDq[6]}]
set_property ODT RTT_60 [get_ports {ddrDq[5]}]
set_property ODT RTT_60 [get_ports {ddrDq[4]}]
set_property ODT RTT_60 [get_ports {ddrDq[3]}]
set_property ODT RTT_60 [get_ports {ddrDq[2]}]
set_property ODT RTT_60 [get_ports {ddrDq[1]}]
set_property ODT RTT_60 [get_ports {ddrDq[0]}]
set_property ODT RTT_60 [get_ports {ddrDqsN[7]}]
set_property ODT RTT_60 [get_ports {ddrDqsN[6]}]
set_property ODT RTT_60 [get_ports {ddrDqsN[5]}]
set_property ODT RTT_60 [get_ports {ddrDqsN[4]}]
set_property ODT RTT_60 [get_ports {ddrDqsN[3]}]
set_property ODT RTT_60 [get_ports {ddrDqsN[2]}]
set_property ODT RTT_60 [get_ports {ddrDqsN[1]}]
set_property ODT RTT_60 [get_ports {ddrDqsN[0]}]
set_property ODT RTT_60 [get_ports {ddrDqsP[7]}]
set_property ODT RTT_60 [get_ports {ddrDqsP[6]}]
set_property ODT RTT_60 [get_ports {ddrDqsP[5]}]
set_property ODT RTT_60 [get_ports {ddrDqsP[4]}]
set_property ODT RTT_60 [get_ports {ddrDqsP[3]}]
set_property ODT RTT_60 [get_ports {ddrDqsP[2]}]
set_property ODT RTT_60 [get_ports {ddrDqsP[1]}]
set_property ODT RTT_60 [get_ports {ddrDqsP[0]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[63]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[62]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[61]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[60]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[59]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[58]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[57]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[56]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[55]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[54]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[53]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[52]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[51]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[50]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[49]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[48]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[47]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[46]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[45]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[44]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[43]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[42]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[41]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[40]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[39]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[38]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[37]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[36]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[35]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[34]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[33]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[32]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[31]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[30]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[29]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[28]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[27]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[26]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[25]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[24]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[23]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[22]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[21]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[20]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[19]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[18]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[17]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[16]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[15]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[14]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[13]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[12]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[11]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[10]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[9]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[8]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[7]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[6]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[5]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[4]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[3]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[2]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[1]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDq[0]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDqsN[7]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDqsN[6]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDqsN[5]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDqsN[4]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDqsN[3]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDqsN[2]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDqsN[1]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDqsN[0]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDqsP[7]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDqsP[6]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDqsP[5]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDqsP[4]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDqsP[3]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDqsP[2]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDqsP[1]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDqsP[0]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[63]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[62]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[61]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[60]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[59]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[58]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[57]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[56]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[55]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[54]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[53]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[52]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[51]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[50]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[49]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[48]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[47]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[46]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[45]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[44]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[43]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[42]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[41]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[40]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[39]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[38]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[37]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[36]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[35]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[34]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[33]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[32]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[31]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[30]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[29]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[28]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[27]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[26]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[25]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[24]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[23]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[22]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[21]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[20]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[19]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[18]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[17]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[16]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[15]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[14]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[13]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[12]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[11]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[10]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[9]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[8]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[7]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[6]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[5]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[4]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[3]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[2]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[1]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDq[0]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDqsN[7]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDqsN[6]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDqsN[5]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDqsN[4]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDqsN[3]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDqsN[2]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDqsN[1]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDqsN[0]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDqsP[7]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDqsP[6]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDqsP[5]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDqsP[4]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDqsP[3]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDqsP[2]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDqsP[1]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDqsP[0]}]
set_property DATA_RATE SDR [get_ports {ddrCsL[0]}]
set_property ODT RTT_60 [get_ports {ddrDm[7]}]
set_property ODT RTT_60 [get_ports {ddrDm[6]}]
set_property ODT RTT_60 [get_ports {ddrDm[5]}]
set_property ODT RTT_60 [get_ports {ddrDm[4]}]
set_property ODT RTT_60 [get_ports {ddrDm[3]}]
set_property ODT RTT_60 [get_ports {ddrDm[2]}]
set_property ODT RTT_60 [get_ports {ddrDm[1]}]
set_property ODT RTT_60 [get_ports {ddrDm[0]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDm[7]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDm[6]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDm[5]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDm[4]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDm[3]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDm[2]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDm[1]}]
set_property EQUALIZATION EQ_LEVEL2 [get_ports {ddrDm[0]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDm[7]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDm[6]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDm[5]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDm[4]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDm[3]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDm[2]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDm[1]}]
set_property PRE_EMPHASIS RDRV_240 [get_ports {ddrDm[0]}]
set_property DATA_RATE DDR [get_ports {ddrDm[7]}]
set_property DATA_RATE DDR [get_ports {ddrDm[6]}]
set_property DATA_RATE DDR [get_ports {ddrDm[5]}]
set_property DATA_RATE DDR [get_ports {ddrDm[4]}]
set_property DATA_RATE DDR [get_ports {ddrDm[3]}]
set_property DATA_RATE DDR [get_ports {ddrDm[2]}]
set_property DATA_RATE DDR [get_ports {ddrDm[1]}]
set_property DATA_RATE DDR [get_ports {ddrDm[0]}]
set_property DATA_RATE SDR [get_ports {ddrA[16]}]
set_property DATA_RATE SDR [get_ports {ddrA[15]}]
set_property DATA_RATE SDR [get_ports {ddrA[14]}]
set_property DATA_RATE SDR [get_ports {ddrA[13]}]
set_property DATA_RATE SDR [get_ports {ddrA[12]}]
set_property DATA_RATE SDR [get_ports {ddrA[11]}]
set_property DATA_RATE SDR [get_ports {ddrA[10]}]
set_property DATA_RATE SDR [get_ports {ddrA[9]}]
set_property DATA_RATE SDR [get_ports {ddrA[8]}]
set_property DATA_RATE SDR [get_ports {ddrA[7]}]
set_property DATA_RATE SDR [get_ports {ddrA[6]}]
set_property DATA_RATE SDR [get_ports {ddrA[5]}]
set_property DATA_RATE SDR [get_ports {ddrA[4]}]
set_property DATA_RATE SDR [get_ports {ddrA[3]}]
set_property DATA_RATE SDR [get_ports {ddrA[2]}]
set_property DATA_RATE SDR [get_ports {ddrA[1]}]
set_property DATA_RATE SDR [get_ports {ddrA[0]}]
set_property DATA_RATE SDR [get_ports ddrActL]
set_property DATA_RATE SDR [get_ports {ddrBa[1]}]
set_property DATA_RATE SDR [get_ports {ddrBa[0]}]
set_property DATA_RATE SDR [get_ports {ddrBg[0]}]
set_property DATA_RATE SDR [get_ports {ddrCke[0]}]
set_property DATA_RATE SDR [get_ports {ddrOdt[0]}]
set_property DATA_RATE DDR [get_ports {ddrDq[63]}]
set_property DATA_RATE DDR [get_ports {ddrDq[62]}]
set_property DATA_RATE DDR [get_ports {ddrDq[61]}]
set_property DATA_RATE DDR [get_ports {ddrDq[60]}]
set_property DATA_RATE DDR [get_ports {ddrDq[59]}]
set_property DATA_RATE DDR [get_ports {ddrDq[58]}]
set_property DATA_RATE DDR [get_ports {ddrDq[57]}]
set_property DATA_RATE DDR [get_ports {ddrDq[56]}]
set_property DATA_RATE DDR [get_ports {ddrDq[55]}]
set_property DATA_RATE DDR [get_ports {ddrDq[54]}]
set_property DATA_RATE DDR [get_ports {ddrDq[53]}]
set_property DATA_RATE DDR [get_ports {ddrDq[52]}]
set_property DATA_RATE DDR [get_ports {ddrDq[51]}]
set_property DATA_RATE DDR [get_ports {ddrDq[50]}]
set_property DATA_RATE DDR [get_ports {ddrDq[49]}]
set_property DATA_RATE DDR [get_ports {ddrDq[48]}]
set_property DATA_RATE DDR [get_ports {ddrDq[47]}]
set_property DATA_RATE DDR [get_ports {ddrDq[46]}]
set_property DATA_RATE DDR [get_ports {ddrDq[45]}]
set_property DATA_RATE DDR [get_ports {ddrDq[44]}]
set_property DATA_RATE DDR [get_ports {ddrDq[43]}]
set_property DATA_RATE DDR [get_ports {ddrDq[42]}]
set_property DATA_RATE DDR [get_ports {ddrDq[41]}]
set_property DATA_RATE DDR [get_ports {ddrDq[40]}]
set_property DATA_RATE DDR [get_ports {ddrDq[39]}]
set_property DATA_RATE DDR [get_ports {ddrDq[38]}]
set_property DATA_RATE DDR [get_ports {ddrDq[37]}]
set_property DATA_RATE DDR [get_ports {ddrDq[36]}]
set_property DATA_RATE DDR [get_ports {ddrDq[35]}]
set_property DATA_RATE DDR [get_ports {ddrDq[34]}]
set_property DATA_RATE DDR [get_ports {ddrDq[33]}]
set_property DATA_RATE DDR [get_ports {ddrDq[32]}]
set_property DATA_RATE DDR [get_ports {ddrDq[31]}]
set_property DATA_RATE DDR [get_ports {ddrDq[30]}]
set_property DATA_RATE DDR [get_ports {ddrDq[29]}]
set_property DATA_RATE DDR [get_ports {ddrDq[28]}]
set_property DATA_RATE DDR [get_ports {ddrDq[27]}]
set_property DATA_RATE DDR [get_ports {ddrDq[26]}]
set_property DATA_RATE DDR [get_ports {ddrDq[25]}]
set_property DATA_RATE DDR [get_ports {ddrDq[24]}]
set_property DATA_RATE DDR [get_ports {ddrDq[23]}]
set_property DATA_RATE DDR [get_ports {ddrDq[22]}]
set_property DATA_RATE DDR [get_ports {ddrDq[21]}]
set_property DATA_RATE DDR [get_ports {ddrDq[20]}]
set_property DATA_RATE DDR [get_ports {ddrDq[19]}]
set_property DATA_RATE DDR [get_ports {ddrDq[18]}]
set_property DATA_RATE DDR [get_ports {ddrDq[17]}]
set_property DATA_RATE DDR [get_ports {ddrDq[16]}]
set_property DATA_RATE DDR [get_ports {ddrDq[15]}]
set_property DATA_RATE DDR [get_ports {ddrDq[14]}]
set_property DATA_RATE DDR [get_ports {ddrDq[13]}]
set_property DATA_RATE DDR [get_ports {ddrDq[12]}]
set_property DATA_RATE DDR [get_ports {ddrDq[11]}]
set_property DATA_RATE DDR [get_ports {ddrDq[10]}]
set_property DATA_RATE DDR [get_ports {ddrDq[9]}]
set_property DATA_RATE DDR [get_ports {ddrDq[8]}]
set_property DATA_RATE DDR [get_ports {ddrDq[7]}]
set_property DATA_RATE DDR [get_ports {ddrDq[6]}]
set_property DATA_RATE DDR [get_ports {ddrDq[5]}]
set_property DATA_RATE DDR [get_ports {ddrDq[4]}]
set_property DATA_RATE DDR [get_ports {ddrDq[3]}]
set_property DATA_RATE DDR [get_ports {ddrDq[2]}]
set_property DATA_RATE DDR [get_ports {ddrDq[1]}]
set_property DATA_RATE DDR [get_ports {ddrDq[0]}]
set_property DATA_RATE DDR [get_ports {ddrDqsN[7]}]
set_property DATA_RATE DDR [get_ports {ddrDqsN[6]}]
set_property DATA_RATE DDR [get_ports {ddrDqsN[5]}]
set_property DATA_RATE DDR [get_ports {ddrDqsN[4]}]
set_property DATA_RATE DDR [get_ports {ddrDqsN[3]}]
set_property DATA_RATE DDR [get_ports {ddrDqsN[2]}]
set_property DATA_RATE DDR [get_ports {ddrDqsN[1]}]
set_property DATA_RATE DDR [get_ports {ddrDqsN[0]}]
set_property DATA_RATE DDR [get_ports {ddrDqsP[7]}]
set_property DATA_RATE DDR [get_ports {ddrDqsP[6]}]
set_property DATA_RATE DDR [get_ports {ddrDqsP[5]}]
set_property DATA_RATE DDR [get_ports {ddrDqsP[4]}]
set_property DATA_RATE DDR [get_ports {ddrDqsP[3]}]
set_property DATA_RATE DDR [get_ports {ddrDqsP[2]}]
set_property DATA_RATE DDR [get_ports {ddrDqsP[1]}]
set_property DATA_RATE DDR [get_ports {ddrDqsP[0]}]
set_property DATA_RATE DDR [get_ports {ddrCkN[0]}]
set_property DATA_RATE DDR [get_ports {ddrCkP[0]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddrDqsP[0]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddrDqsP[1]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddrDqsP[2]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddrDqsP[3]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddrDqsP[4]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddrDqsP[5]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddrDqsP[6]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddrDqsP[7]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddrDqsN[0]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddrDqsN[1]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddrDqsN[2]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddrDqsN[3]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddrDqsN[4]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddrDqsN[5]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddrDqsN[6]}]
set_property IOSTANDARD DIFF_POD12_DCI [get_ports {ddrDqsN[7]}]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports {ddrCkP[0]}]
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports {ddrCkN[0]}]
set_property IOSTANDARD LVCMOS12 [get_ports ddrRstL]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDm[0]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDm[1]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDm[2]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDm[3]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDm[4]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDm[5]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDm[6]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDm[7]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[0]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[1]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[2]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[3]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[4]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[5]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[6]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[7]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[8]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[9]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[10]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[11]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[12]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[13]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[14]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[15]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[16]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[17]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[18]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[19]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[20]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[21]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[22]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[23]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[24]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[25]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[26]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[27]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[28]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[29]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[30]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[31]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[32]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[33]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[34]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[35]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[36]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[37]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[38]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[39]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[40]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[41]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[42]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[43]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[44]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[45]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[46]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[47]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[48]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[49]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[50]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[51]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[52]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[53]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[54]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[55]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[56]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[57]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[58]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[59]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[60]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[61]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[62]}]
set_property IOSTANDARD POD12_DCI [get_ports {ddrDq[63]}]
set_property IOSTANDARD SSTL12_DCI [get_ports ddrActL]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddrA[0]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddrA[1]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddrA[2]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddrA[3]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddrA[4]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddrA[5]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddrA[6]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddrA[7]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddrA[8]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddrA[9]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddrA[10]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddrA[11]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddrA[12]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddrA[13]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddrA[14]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddrA[15]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddrA[16]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddrBa[0]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddrBa[1]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddrBg[0]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddrCsL[0]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddrCke[0]}]
set_property IOSTANDARD SSTL12_DCI [get_ports {ddrOdt[0]}]
set_property SLEW FAST [get_ports {ddrCsL[0]}]
set_property SLEW FAST [get_ports {ddrDm[0]}]
set_property SLEW FAST [get_ports {ddrDm[1]}]
set_property SLEW FAST [get_ports {ddrDm[2]}]
set_property SLEW FAST [get_ports {ddrDm[3]}]
set_property SLEW FAST [get_ports {ddrDm[4]}]
set_property SLEW FAST [get_ports {ddrDm[5]}]
set_property SLEW FAST [get_ports {ddrDm[6]}]
set_property SLEW FAST [get_ports {ddrDm[7]}]
set_property SLEW FAST [get_ports {ddrA[16]}]
set_property SLEW FAST [get_ports {ddrA[15]}]
set_property SLEW FAST [get_ports {ddrA[14]}]
set_property SLEW FAST [get_ports {ddrA[13]}]
set_property SLEW FAST [get_ports {ddrA[12]}]
set_property SLEW FAST [get_ports {ddrA[11]}]
set_property SLEW FAST [get_ports {ddrA[10]}]
set_property SLEW FAST [get_ports {ddrA[9]}]
set_property SLEW FAST [get_ports {ddrA[8]}]
set_property SLEW FAST [get_ports {ddrA[7]}]
set_property SLEW FAST [get_ports {ddrA[6]}]
set_property SLEW FAST [get_ports {ddrA[5]}]
set_property SLEW FAST [get_ports {ddrA[4]}]
set_property SLEW FAST [get_ports {ddrA[3]}]
set_property SLEW FAST [get_ports {ddrA[2]}]
set_property SLEW FAST [get_ports {ddrA[1]}]
set_property SLEW FAST [get_ports {ddrA[0]}]
set_property SLEW FAST [get_ports {ddrBa[1]}]
set_property SLEW FAST [get_ports {ddrBa[0]}]
set_property SLEW FAST [get_ports {ddrBg[0]}]
set_property SLEW FAST [get_ports {ddrCkN[0]}]
set_property SLEW FAST [get_ports {ddrCkP[0]}]
set_property SLEW FAST [get_ports {ddrCke[0]}]
set_property SLEW FAST [get_ports {ddrOdt[0]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports ddrActL]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrA[0]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrA[10]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrA[11]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrA[12]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrA[13]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrA[14]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrA[15]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrA[16]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrA[1]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrA[2]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrA[3]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrA[4]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrA[5]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrA[6]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrA[7]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrA[8]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrA[9]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrBa[0]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrBa[1]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrBg[0]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrCkP[0]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrCkN[0]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrCke[0]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrCsL[0]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDm[0]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDm[1]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDm[2]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDm[3]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDm[4]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDm[5]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDm[6]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDm[7]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[0]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[10]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[11]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[12]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[13]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[14]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[15]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[16]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[17]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[18]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[19]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[1]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[20]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[21]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[22]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[23]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[24]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[25]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[26]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[27]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[28]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[29]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[2]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[30]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[31]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[32]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[33]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[34]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[35]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[36]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[37]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[38]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[39]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[3]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[40]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[41]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[42]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[43]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[44]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[45]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[46]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[47]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[48]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[49]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[4]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[50]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[51]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[52]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[53]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[54]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[55]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[56]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[57]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[58]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[59]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[5]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[60]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[61]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[62]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[63]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[6]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[7]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[8]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDq[9]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDqsP[0]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDqsP[1]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDqsP[2]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDqsP[3]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDqsP[4]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDqsP[5]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDqsP[6]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDqsP[7]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDqsN[0]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDqsN[1]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDqsN[2]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDqsN[3]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDqsN[4]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDqsN[5]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDqsN[6]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrDqsN[7]}]
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {ddrOdt[0]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDm[0]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDm[1]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDm[2]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDm[3]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDm[4]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDm[5]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDm[6]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDm[7]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[0]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[1]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[2]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[3]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[4]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[5]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[6]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[7]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[8]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[9]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[10]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[11]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[12]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[13]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[14]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[15]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[16]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[17]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[18]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[19]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[20]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[21]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[22]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[23]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[24]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[25]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[26]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[27]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[28]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[29]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[30]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[31]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[32]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[33]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[34]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[35]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[36]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[37]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[38]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[39]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[40]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[41]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[42]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[43]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[44]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[45]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[46]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[47]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[48]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[49]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[50]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[51]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[52]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[53]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[54]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[55]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[56]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[57]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[58]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[59]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[60]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[61]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[62]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDq[63]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDqsP[0]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDqsP[1]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDqsP[2]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDqsP[3]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDqsP[4]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDqsP[5]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDqsP[6]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDqsP[7]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDqsN[0]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDqsN[1]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDqsN[2]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDqsN[3]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDqsN[4]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDqsN[5]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDqsN[6]}]
set_property IBUF_LOW_PWR FALSE [get_ports {ddrDqsN[7]}]

set_property IOSTANDARD DIFF_SSTL12 [get_ports ddrClkP]
set_property IOSTANDARD DIFF_SSTL12 [get_ports ddrClkN]

##############################################################################

set_clock_groups -asynchronous -group [get_clocks -of_objects [get_pins U_Core/REAL_CPU.U_CPU/U_Pll/PllGen.U_Pll/CLKOUT0]] -group [get_clocks -of_objects [get_pins U_Core/REAL_CPU.U_CPU/U_Pll/PllGen.U_Pll/CLKOUT1]]

set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks {ddrClkP}] -group [get_clocks -of_objects [get_pins U_Core/REAL_CPU.U_CPU/U_Pll/PllGen.U_Pll/CLKOUT0]]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks {ddrClkP}] -group [get_clocks -of_objects [get_pins U_Core/REAL_CPU.U_CPU/U_Pll/PllGen.U_Pll/CLKOUT1]]
set_clock_groups -asynchronous -group [get_clocks -include_generated_clocks {ddrClkP}] -group [get_clocks -include_generated_clocks {plClkP}]

##############################################################################
