
# https://github.com/Xilinx/embeddedsw/blob/master/XilinxProcessorIPLib/drivers/rfdc/src/xrfdc.h#L415-L451
class XRFdc_MTS_DTC_Settings:
    def __init__(self):
        self.RefTile = 0
        self.IsPLL = 0
        self.Target = [0] * 4
        self.Scan_Mode = 0
        self.DTC_Code = [0] * 4
        self.Num_Windows = [0] * 4
        self.Max_Gap = [0] * 4
        self.Min_Gap = [0] * 4
        self.Max_Overlap = [0] * 4

class XRFdc_MultiConverter_Sync_Config:
    def __init__(self):
        self.RefTile = 0
        self.Tiles = 0
        self.Target_Latency = 0
        self.Offset = [0] * 4
        self.Latency = [0] * 4
        self.Marker_Delay = 0
        self.SysRef_Enable = 0
        self.DTC_Set_PLL = XRFdc_MTS_DTC_Settings()
        self.DTC_Set_T1 = XRFdc_MTS_DTC_Settings()

class XRFdc_MTS_Marker:
    def __init__(self):
        self.Count = [0] * 4
        self.Loc = [0] * 4

# https://github.com/Xilinx/embeddedsw/blob/xilinx_v2023.2/XilinxProcessorIPLib/drivers/rfdc/src/xrfdc.h#L815-L850
def XRFDC_MAX(x, y):
    return x if x > y else y
def XRFDC_MIN(x, y):
    return x if x < y else y
    
XRFDC_SUCCESS = 0
XRFDC_FAILURE = 1
XRFDC_GEN3 = 2
XRFDC_COMPONENT_IS_READY = 0x11111111
XRFDC_NUM_SLICES_HSADC = 2
XRFDC_NUM_SLICES_LSADC = 4
XRFDC_REGION_SIZE = 0x40000
XRFDC_IP_BASE = 0x0

def XRFDC_DRP_BASE(type, tile): 
    return XRFDC_ADC_TILE_DRP_ADDR(tile) if (type == XRFDC_ADC_TILE) else XRFDC_DAC_TILE_DRP_ADDR(tile)
def XRFDC_CTRL_STS_BASE(type, tile): 
    return XRFDC_ADC_TILE_CTRL_STATS_ADDR(tile) if (type == XRFDC_ADC_TILE) else XRFDC_DAC_TILE_CTRL_STATS_ADDR(tile)
def XRFDC_BLOCK_BASE(Type, Tile, Block): 
    return XRFDC_ADC_TILE_DRP_ADDR(tile) + XRFDC_BLOCK_ADDR_OFFSET(Block) if (type == XRFDC_ADC_TILE) else XRFDC_DAC_TILE_DRP_ADDR(tile) + XRFDC_BLOCK_ADDR_OFFSET(Block)

# https://github.com/Xilinx/embeddedsw/blob/xilinx_v2023.2/XilinxProcessorIPLib/drivers/rfdc/src/xrfdc.h#L852-L1127
XRFDC_ADC_TILE = 0
XRFDC_DAC_TILE = 1
XRFDC_TILE_ID_MAX = 0x3
XRFDC_BLOCK_ID_MAX = 0x3
XRFDC_EVNT_SRC_IMMEDIATE = 0x00000000
XRFDC_EVNT_SRC_SLICE = 0x00000001
XRFDC_EVNT_SRC_TILE = 0x00000002
XRFDC_EVNT_SRC_SYSREF = 0x00000003
XRFDC_EVNT_SRC_MARKER = 0x00000004
XRFDC_EVNT_SRC_PL = 0x00000005
XRFDC_EVENT_MIXER = 0x00000001
XRFDC_EVENT_CRSE_DLY = 0x00000002
XRFDC_EVENT_QMC = 0x00000004
XRFDC_SELECT_ALL_TILES = -1
XRFDC_ADC_4GSPS = 1

XRFDC_CRSE_DLY_MAX = 0x7
XRFDC_CRSE_DLY_MAX_EXT = 0x28
XRFDC_NCO_FREQ_MULTIPLIER = (0x1 << 48)
XRFDC_NCO_PHASE_MULTIPLIER = (1 << 17)
XRFDC_QMC_PHASE_MULT = (1 << 11) 
XRFDC_QMC_GAIN_MULT = (1 << 14) 

XRFDC_DATA_TYPE_IQ = 0x00000001
XRFDC_DATA_TYPE_REAL = 0x00000000

XRFDC_TRSHD_OFF = 0x0
XRFDC_TRSHD_STICKY_OVER = 0x00000001
XRFDC_TRSHD_STICKY_UNDER = 0x00000002
XRFDC_TRSHD_HYSTERISIS = 0x00000003

XRFDC_MIXER_MODE_OFF = 0x0
XRFDC_MIXER_MODE_C2C = 0x1
XRFDC_MIXER_MODE_C2R = 0x2
XRFDC_MIXER_MODE_R2C = 0x3
XRFDC_MIXER_MODE_R2R = 0x4

XRFDC_I_IQ_COS_MINSIN = 0x00000C00
XRFDC_Q_IQ_SIN_COS = 0x00001000
XRFDC_EN_I_IQ = 0x00000001
XRFDC_EN_Q_IQ = 0x00000004

XRFDC_MIXER_TYPE_COARSE = 0x1
XRFDC_MIXER_TYPE_FINE = 0x2

XRFDC_MIXER_TYPE_OFF = 0x0
XRFDC_MIXER_TYPE_DISABLED = 0x3

XRFDC_COARSE_MIX_OFF = 0x0
XRFDC_COARSE_MIX_SAMPLE_FREQ_BY_TWO = 0x2
XRFDC_COARSE_MIX_SAMPLE_FREQ_BY_FOUR = 0x4
XRFDC_COARSE_MIX_MIN_SAMPLE_FREQ_BY_FOUR = 0x8
XRFDC_COARSE_MIX_BYPASS = 0x10

XRFDC_COARSE_MIX_MODE_C2C_C2R = 0x1
XRFDC_COARSE_MIX_MODE_R2C = 0x2

XRFDC_CRSE_MIX_OFF = 0x924
XRFDC_CRSE_MIX_BYPASS = 0x0
XRFDC_CRSE_4GSPS_ODD_FSBYTWO = 0x492
XRFDC_CRSE_MIX_I_ODD_FSBYFOUR = 0x2CB
XRFDC_CRSE_MIX_Q_ODD_FSBYFOUR = 0x659
XRFDC_CRSE_MIX_I_Q_FSBYTWO = 0x410
XRFDC_CRSE_MIX_I_FSBYFOUR = 0x298
XRFDC_CRSE_MIX_Q_FSBYFOUR = 0x688
XRFDC_CRSE_MIX_I_MINFSBYFOUR = 0x688
XRFDC_CRSE_MIX_Q_MINFSBYFOUR = 0x298
XRFDC_CRSE_MIX_R_I_FSBYFOUR = 0x8A0
XRFDC_CRSE_MIX_R_Q_FSBYFOUR = 0x70C
XRFDC_CRSE_MIX_R_I_MINFSBYFOUR = 0x8A0
XRFDC_CRSE_MIX_R_Q_MINFSBYFOUR = 0x31C

XRFDC_MIXER_SCALE_AUTO = 0x0
XRFDC_MIXER_SCALE_1P0 = 0x1
XRFDC_MIXER_SCALE_0P7 = 0x2

XRFDC_MIXER_PHASE_OFFSET_UP_LIMIT = 180.0
XRFDC_MIXER_PHASE_OFFSET_LOW_LIMIT = (-180.0)
XRFDC_UPDATE_THRESHOLD_0 = 0x1
XRFDC_UPDATE_THRESHOLD_1 = 0x2
XRFDC_UPDATE_THRESHOLD_BOTH = 0x4
XRFDC_THRESHOLD_CLRMD_MANUAL_CLR = 0x1
XRFDC_THRESHOLD_CLRMD_AUTO_CLR = 0x2
XRFDC_DECODER_MAX_SNR_MODE = 0x1
XRFDC_DECODER_MAX_LINEARITY_MODE = 0x2
XRFDC_OUTPUT_CURRENT_32MA = 32
XRFDC_OUTPUT_CURRENT_20MA = 20

XRFDC_MIXER_MODE_IQ = 0x1
XRFDC_ADC_MIXER_MODE_IQ = 0x1
XRFDC_DAC_MIXER_MODE_REAL = 0x2

XRFDC_ODD_NYQUIST_ZONE = 0x1
XRFDC_EVEN_NYQUIST_ZONE = 0x2

XRFDC_INTERP_DECIM_OFF = 0x0
XRFDC_INTERP_DECIM_1X = 0x1
XRFDC_INTERP_DECIM_2X = 0x2
XRFDC_INTERP_DECIM_3X = 0x3
XRFDC_INTERP_DECIM_4X = 0x4
XRFDC_INTERP_DECIM_5X = 0x5
XRFDC_INTERP_DECIM_6X = 0x6
XRFDC_INTERP_DECIM_8X = 0x8
XRFDC_INTERP_DECIM_10X = 0xA
XRFDC_INTERP_DECIM_12X = 0xC
XRFDC_INTERP_DECIM_16X = 0x10
XRFDC_INTERP_DECIM_20X = 0x14
XRFDC_INTERP_DECIM_24X = 0x18
XRFDC_INTERP_DECIM_40X = 0x28

XRFDC_FAB_CLK_DIV1 = 0x1
XRFDC_FAB_CLK_DIV2 = 0x2
XRFDC_FAB_CLK_DIV4 = 0x3
XRFDC_FAB_CLK_DIV8 = 0x4
XRFDC_FAB_CLK_DIV16 = 0x5

XRFDC_CALIB_MODE_AUTO = 0x0
XRFDC_CALIB_MODE1 = 0x1
XRFDC_CALIB_MODE2 = 0x2
XRFDC_CALIB_MODE_MIXED = 0x0
XRFDC_CALIB_MODE_ABS_DIFF = 0x1
XRFDC_CALIB_MODE_NEG_ABS_SUM = 0x2
XRFDC_TI_DCB_MODE1_4GSPS = 0x00007800
XRFDC_TI_DCB_MODE1_2GSPS = 0x00005000

XRFDC_PLL_UNLOCKED = 0x1
XRFDC_PLL_LOCKED = 0x2

XRFDC_EXTERNAL_CLK = 0x0
XRFDC_INTERNAL_PLL_CLK = 0x1

PLL_FPDIV_MIN = 13
PLL_FPDIV_MAX = 128
PLL_DIVIDER_MIN = 2
PLL_DIVIDER_MIN_GEN3 = 1
PLL_DIVIDER_MAX = 28
VCO_RANGE_MIN = 8500
VCO_RANGE_MAX = 13200
VCO_RANGE_ADC_MIN = 8500
VCO_RANGE_ADC_MAX = 12800
VCO_RANGE_DAC_MIN = 7800
VCO_RANGE_DAC_MAX = 13800
XRFDC_PLL_LPF1_VAL = 0x6
XRFDC_PLL_CRS2_VAL = 0x7008
XRFDC_VCO_UPPER_BAND = 0x0
XRFDC_VCO_LOWER_BAND = 0x1
XRFDC_REF_CLK_DIV_1 = 0x1
XRFDC_REF_CLK_DIV_2 = 0x2
XRFDC_REF_CLK_DIV_3 = 0x3
XRFDC_REF_CLK_DIV_4 = 0x4

XRFDC_SINGLEBAND_MODE = 0x1
XRFDC_MULTIBAND_MODE_2X = 0x2
XRFDC_MULTIBAND_MODE_4X = 0x4

XRFDC_MB_DATATYPE_C2C = 0x1
XRFDC_MB_DATATYPE_R2C = 0x2
XRFDC_MB_DATATYPE_C2R = 0x4

XRFDC_MB_DUAL_BAND = 2
XRFDC_MB_QUAD_BAND = 4

XRFDC_SB_C2C_BLK0 = 0x82
XRFDC_SB_C2C_BLK1 = 0x64
XRFDC_SB_C2R = 0x40
XRFDC_MB_C2C_BLK0 = 0x5E
XRFDC_MB_C2C_BLK1 = 0x5D
XRFDC_MB_C2R_BLK0 = 0x5C
XRFDC_MB_C2R_BLK1 = 0x0

XRFDC_MIXER_MODE_BYPASS = 0x2

XRFDC_LINK_COUPLING_DC = 0x0
XRFDC_LINK_COUPLING_AC = 0x1

XRFDC_MB_MODE_SB = 0x0
XRFDC_MB_MODE_2X_BLK01 = 0x1
XRFDC_MB_MODE_2X_BLK23 = 0x2
XRFDC_MB_MODE_2X_BLK01_BLK23 = 0x3
XRFDC_MB_MODE_4X = 0x4
XRFDC_MB_MODE_2X_BLK01_BLK23_ALT = 0x5

XRFDC_MILLI = 1000
XRFDC_MICRO = 1000000
XRFDC_DAC_SAMPLING_MIN = 500
XRFDC_DAC_SAMPLING_MAX = 6554
XRFDC_ADC_4G_SAMPLING_MIN = 1000
XRFDC_ADC_4G_SAMPLING_MAX = 4116
XRFDC_ADC_2G_SAMPLING_MIN = 500
XRFDC_ADC_2G_SAMPLING_MAX = 2058
XRFDC_REFFREQ_MIN = 102.40625
XRFDC_REFFREQ_MAX = 614.0

XRFDC_DIGITALPATH_ENABLE = 0x1
XRFDC_ANALOGPATH_ENABLE = 0x1

XRFDC_BLK_ID0 = 0x0
XRFDC_BLK_ID1 = 0x1
XRFDC_BLK_ID2 = 0x2
XRFDC_BLK_ID3 = 0x3
XRFDC_BLK_ID4 = 0x4

XRFDC_BLK_ID_NONE = -1
XRFDC_BLK_ID_ALL = -1
XRFDC_BLK_ID_INV = 0x4

XRFDC_TILE_ID0 = 0x0
XRFDC_TILE_ID1 = 0x1
XRFDC_TILE_ID2 = 0x2
XRFDC_TILE_ID3 = 0x3
XRFDC_TILE_ID4 = 0x4

XRFDC_TILE_ID_INV = 0x4

XRFDC_NUM_OF_BLKS1 = 0x1
XRFDC_NUM_OF_BLKS2 = 0x2
XRFDC_NUM_OF_BLKS3 = 0x3
XRFDC_NUM_OF_BLKS4 = 0x4

XRFDC_NUM_OF_TILES1 = 0x1
XRFDC_NUM_OF_TILES2 = 0x2
XRFDC_NUM_OF_TILES3 = 0x3
XRFDC_NUM_OF_TILES4 = 0x4

XRFDC_SM_STATE0 = 0x0
XRFDC_SM_STATE1 = 0x1
XRFDC_SM_STATE3 = 0x3
XRFDC_SM_STATE7 = 0x7
XRFDC_SM_STATE15 = 0xF

XRFDC_STATE_OFF = 0x0
XRFDC_STATE_SHUTDOWN = 0x1
XRFDC_STATE_PWRUP = 0x3
XRFDC_STATE_CLK_DET = 0x6
XRFDC_STATE_CAL = 0xB
XRFDC_STATE_FULL = 0xF

XRFDC_DECIM_4G_DATA_TYPE = 0x3
XRFDC_DECIM_2G_IQ_DATA_TYPE = 0x2

XRFDC_DAC_MAX_WR_FAB_RATE = 16
def XRFDC_ADC_MAX_RD_FAB_RATE(X):
    return 8 if (x < XRFDC_GEN3) else 12

XRFDC_MIN_PHASE_CORR_FACTOR = -26.5
XRFDC_MAX_PHASE_CORR_FACTOR = 26.5
XRFDC_MAX_GAIN_CORR_FACTOR = 2.0
XRFDC_MIN_GAIN_CORR_FACTOR = 0.0

XRFDC_FAB_RATE_16 = 16
XRFDC_FAB_RATE_8 = 8
XRFDC_FAB_RATE_4 = 4
XRFDC_FAB_RATE_2 = 2
XRFDC_FAB_RATE_1 = 1

XRFDC_HSCOM_PWR_STATS_PLL = 0xFFC0
XRFDC_HSCOM_PWR_STATS_EXTERNAL = 0xF240
XRFDC_HSCOM_PWR_STATS_RX_EXT = 0xF2FC
XRFDC_HSCOM_PWR_STATS_DIST_EXT = 0xF0FE
XRFDC_HSCOM_PWR_STATS_RX_PLL = 0xFFFC
XRFDC_HSCOM_PWR_STATS_DIST_PLL = 0xFDFE
XRFDC_HSCOM_PWR_STATS_RX_EXT_DIV = 0xF2FC
XRFDC_HSCOM_PWR_STATS_DIST_EXT_DIV = 0xF0FE
XRFDC_HSCOM_PWR_STATS_DIST_EXT_SRC = 0xF2FC
XRFDC_HSCOM_PWR_STATS_DIST_EXT_DIV_SRC = 0xF2FC

XRFDC_CLK_DST_TILE_231 = 0
XRFDC_CLK_DST_TILE_230 = 1
XRFDC_CLK_DST_TILE_229 = 2
XRFDC_CLK_DST_TILE_228 = 3
XRFDC_CLK_DST_TILE_227 = 4
XRFDC_CLK_DST_TILE_226 = 5
XRFDC_CLK_DST_TILE_225 = 6
XRFDC_CLK_DST_TILE_224 = 7
XRFDC_CLK_DST_INVALID = 0xFF

# https://github.com/Xilinx/embeddedsw/blob/xilinx_v2023.2/XilinxProcessorIPLib/drivers/rfdc/src/xrfdc.h#L1129-L1347
XRFDC_GLBL_OFST_DAC = 0
XRFDC_GLBL_OFST_ADC = 4
def XRFDC_TILE_GLBL_ADDR(X, Y):
    return Y + (XRFDC_GLBL_OFST_ADC if X == XRFDC_ADC_TILE else XRFDC_GLBL_OFST_DAC)

XRFDC_CLK_DISTR_MUX4A_SRC_INT = 0x0008
XRFDC_CLK_DISTR_MUX4A_SRC_STH = 0x0000
XRFDC_CLK_DISTR_MUX6_SRC_OFF = 0x0000
XRFDC_CLK_DISTR_MUX6_SRC_INT = 0x0100
XRFDC_CLK_DISTR_MUX6_SRC_NTH = 0x0080
XRFDC_CLK_DISTR_MUX7_SRC_OFF = 0x0000
XRFDC_CLK_DISTR_MUX7_SRC_STH = 0x0200
XRFDC_CLK_DISTR_MUX7_SRC_INT = 0x0400
XRFDC_CLK_DISTR_MUX8_SRC_NTH = 0x0000
XRFDC_CLK_DISTR_MUX8_SRC_INT = 0x8000
XRFDC_CLK_DISTR_MUX9_SRC_NTH = 0x4000
XRFDC_CLK_DISTR_MUX9_SRC_INT = 0x0000
XRFDC_CLK_DISTR_MUX5A_SRC_PLL = 0x0800
XRFDC_CLK_DISTR_MUX5A_SRC_RX = 0x0040
XRFDC_CLK_DISTR_OFF = (XRFDC_CLK_DISTR_MUX4A_SRC_INT | XRFDC_CLK_DISTR_MUX6_SRC_OFF | XRFDC_CLK_DISTR_MUX7_SRC_OFF | XRFDC_CLK_DISTR_MUX8_SRC_NTH | XRFDC_CLK_DISTR_MUX9_SRC_INT)
XRFDC_CLK_DISTR_LEFTMOST_TILE = 0x0000
XRFDC_CLK_DISTR_CONT_LEFT_EVEN = 0x8208
XRFDC_CLK_DISTR_CONT_LEFT_ODD = 0x8200
XRFDC_CLK_DISTR_RIGHTMOST_TILE = 0x4008
XRFDC_CLK_DISTR_CONT_RIGHT_EVEN = 0x4080
XRFDC_CLK_DISTR_CONT_RIGHT_HWL_ODD = 0x4088

XRFDC_CLK_DISTR_MUX4A_SRC_CLR = 0x0008
XRFDC_CLK_DISTR_MUX6_SRC_CLR = 0x0180
XRFDC_CLK_DISTR_MUX7_SRC_CLR = 0x0600
XRFDC_CLK_DISTR_MUX8_SRC_CLR = 0x8000
XRFDC_CLK_DISTR_MUX9_SRC_CLR = 0x4000

XRFDC_DIST_MAX = 8

XRFDC_NET_CTRL_CLK_REC_PLL = 0x1
XRFDC_NET_CTRL_CLK_REC_DIST_T1 = 0x2
XRFDC_NET_CTRL_CLK_T1_SRC_LOCAL = 0x4
XRFDC_NET_CTRL_CLK_T1_SRC_DIST = 0x8
XRFDC_NET_CTRL_CLK_INPUT_DIST = 0x20
XRFDC_DIST_CTRL_TO_PLL_DIV = 0x10
XRFDC_DIST_CTRL_TO_T1 = 0x20
XRFDC_DIST_CTRL_DIST_SRC_LOCAL = 0x40
XRFDC_DIST_CTRL_DIST_SRC_PLL = 0x800
XRFDC_DIST_CTRL_CLK_T1_SRC_LOCAL = 0x1000
XRFDC_PLLREFDIV_INPUT_OFF = 0x20
XRFDC_PLLREFDIV_INPUT_DIST = 0x40
XRFDC_PLLREFDIV_INPUT_FABRIC = 0x60
XRFDC_PLLOPDIV_INPUT_DIST_LOCAL = 0x800

XRFDC_TILE_SOURCE_RX = 0
XRFDC_TILE_SOURCE_DIST = 1
XRFDC_TILE_SOURCE_FABRIC = 2

XRFDC_DIST_OUT_NONE = 0
XRFDC_DIST_OUT_RX = 1
XRFDC_DIST_OUT_OUTDIV = 2

XRFDC_PLL_SOURCE_NONE = 0
XRFDC_PLL_SOURCE_RX = 1
XRFDC_PLL_SOURCE_OUTDIV = 2

XRFDC_PLL_OUTDIV_MODE_1 = 0x0
XRFDC_PLL_OUTDIV_MODE_2 = 0x1
XRFDC_PLL_OUTDIV_MODE_3 = 0x2
XRFDC_PLL_OUTDIV_MODE_N = 0x3

XRFDC_PLL_OUTDIV_MODE_3_VAL = 0x1

XRFDC_DIVISION_FACTOR_MIN = 1

XRFDC_DITH_ENABLE = 1
XRFDC_DITH_DISABLE = 0

XRFDC_SIGDET_MODE_AVG = 0
XRFDC_SIGDET_MODE_RNDM = 1
XRFDC_SIGDET_TC_2_0 = 0
XRFDC_SIGDET_TC_2_2 = 1
XRFDC_SIGDET_TC_2_4 = 2
XRFDC_SIGDET_TC_2_8 = 3
XRFDC_SIGDET_TC_2_12 = 4
XRFDC_SIGDET_TC_2_14 = 5
XRFDC_SIGDET_TC_2_16 = 6
XRFDC_SIGDET_TC_2_18 = 7

XRFDC_DISABLED = 0
XRFDC_ENABLED = 1

XRFDC_ES1_SI = 0
XRFDC_PROD_SI = 1

XRFDC_CAL_BLOCK_OCB1 = 0
XRFDC_CAL_BLOCK_OCB2 = 1
XRFDC_CAL_BLOCK_GCB = 2
XRFDC_CAL_BLOCK_TSCB = 3

XRFDC_TSCB_TUNE_AUTOCAL = 0x0550
XRFDC_TSCB_TUNE_NOT_AUTOCAL = 0x0440

XRFDC_INV_SYNC_MODE_MAX = 2

XRFDC_INV_SYNC_EN_MAX = 1

XRFDC_CTRL_MASK = 0x0440
XRFDC_EXPORTCTRL_CLKDIST  =0x0400
XRFDC_PREMIUMCTRL_CLKDIST = 0x0040
XRFDC_EXPORTCTRL_VOP = 0x2000
XRFDC_EXPORTCTRL_DSA = 0x0400

XRFDC_DATAPATH_MODE_DUC_0_FSDIVTWO = 1
XRFDC_DATAPATH_MODE_DUC_0_FSDIVFOUR = 2
XRFDC_DATAPATH_MODE_FSDIVFOUR_FSDIVTWO = 3
XRFDC_DATAPATH_MODE_NODUC_0_FSDIVTWO = 4
XRFDC_DAC_INT_MODE_FULL_BW = 0
XRFDC_DAC_INT_MODE_HALF_BW_IMR = 2
XRFDC_DAC_INT_MODE_FULL_BW_BYPASS = 3
XRFDC_DAC_MODE_MAX = XRFDC_DATAPATH_MODE_NODUC_0_FSDIVTWO

XRFDC_FULL_BW_DIVISOR = 1
XRFDC_HALF_BW_DIVISOR = 2

XRFDC_DAC_IMR_MODE_LOWPASS = 0
XRFDC_DAC_IMR_MODE_HIGHPASS = 1
XRFDC_DAC_IMR_MODE_MAX = XRFDC_DAC_IMR_MODE_HIGHPASS

XRFDC_CLOCK_DETECT_CLK = 0x1
XRFDC_CLOCK_DETECT_DIST = 0x2
XRFDC_CLOCK_DETECT_BOTH = 0x3

XRFDC_CAL_UNFREEZE_CALIB = 0
XRFDC_CAL_FREEZE_CALIB = 1
XRFDC_CAL_FRZ_PIN_ENABLE = 0
XRFDC_CAL_FRZ_PIN_DISABLE = 1

XRFDC_CLK_REG_EN_MASK = 0x2000

XRFDC_GEN1_LOW_I = 20000
XRFDC_GEN1_HIGH_I = 32000

def XRFDC_MAX_ATTEN(X):
    return 11.0 if (X == 0) else 27.0
XRFDC_MIN_ATTEN = 0
def XRFDC_STEP_ATTEN(X):
    return 0.5 if (X == 0) else 1.0

XRFDC_DAC_VOP_CTRL_REG_UPDT_MASK = 0x2
XRFDC_DAC_VOP_CTRL_TST_BLD_MASK = 0x1
XRFDC_DAC_VOP_BLDR_LOW_BITS_MASK = 0xF

XRFDC_PLL_LOCK_DLY_CNT = 1000
XRFDC_RESTART_CLR_DLY_CNT = 1000
XRFDC_WAIT_ATTEMPTS_CNT = 10000
XRFDC_STATE_WAIT = 100
XRFDC_RESTART_CLR_WAIT = 1000
XRFDC_PLL_LOCK_WAIT = 1000

XRFDC_CLK_DIV_DP_FIRST_MODE = 0x10
XRFDC_CLK_DIV_DP_OTHER_MODES = 0x20

XRFDC_TILE_STARTED = XRFDC_SM_STATE15

XRFDC_SI_REV_ES = 0
XRFDC_SI_REV_PROD = 1

XRFDC_CG_WAIT_CYCLES = 3
XRFDC_ADC_CG_WAIT_CYCLES = 1

XRFDC_CG_CYCLES_TOTAL_X1_X2_X4_X8 = 0
XRFDC_CG_CYCLES_KEPT_X1_X2_X4_X8 = 1
XRFDC_CG_CYCLES_TOTAL_X3_X6_X12 = 3
XRFDC_CG_CYCLES_KEPT_X3_X6_X12 = 2
XRFDC_CG_CYCLES_TOTAL_X5_X10 = 5
XRFDC_CG_CYCLES_KEPT_X5_X10 = 4
XRFDC_CG_CYCLES_TOTAL_X16 = 2
XRFDC_CG_CYCLES_KEPT_X16 = 1
XRFDC_CG_CYCLES_TOTAL_X20 = 5
XRFDC_CG_CYCLES_KEPT_X20 = 2
XRFDC_CG_CYCLES_TOTAL_X24 = 3
XRFDC_CG_CYCLES_KEPT_X24 = 1
XRFDC_CG_CYCLES_TOTAL_X40 = 5
XRFDC_CG_CYCLES_KEPT_X40 = 1

XRFDC_CG_FIXED_OFS = 2

XRFDC_FIFO_CHANNEL_ACT = 0
XRFDC_FIFO_CHANNEL_OBS = 1
XRFDC_FIFO_CHANNEL_BOTH = 2

XRFDC_PWR_MODE_OFF = 0
XRFDC_PWR_MODE_ON = 1

XRFDC_DUAL_TILE = 2
XRFDC_QUAD_TILE = 4

XRFDC_4ADC_4DAC_TILES = 0
XRFDC_3ADC_2DAC_TILES = 1

XRFDC_MTS_SYSREF_DISABLE = 0
XRFDC_MTS_SYSREF_ENABLE = 1

XRFDC_MTS_SCAN_INIT = 0
XRFDC_MTS_SCAN_RELOAD = 1

XRFDC_MTS_OK = 0
XRFDC_MTS_NOT_SUPPORTED = 1
XRFDC_MTS_TIMEOUT = 2
XRFDC_MTS_MARKER_RUN = 4
XRFDC_MTS_MARKER_MISM = 8
XRFDC_MTS_DELAY_OVER = 16
XRFDC_MTS_TARGET_LOW = 32
XRFDC_MTS_IP_NOT_READY = 64
XRFDC_MTS_DTC_INVALID = 128
XRFDC_MTS_NOT_ENABLED = 512
XRFDC_MTS_SYSREF_GATE_ERROR = 2048
XRFDC_MTS_SYSREF_FREQ_NDONE = 4096
XRFDC_MTS_BAD_REF_TILE = 8192

XRFDC_CAL_AXICLK_MULT = 12.17085774
def XRFDC_CAL_DIV_CUTOFF_FREQ(X):
    return 5.0 if (X == 0) else 2.5
