#!/bin/sh
##############################################################################
## This file is part of 'axi-soc-ultra-plus-core'.
## It is subject to the license terms in the LICENSE.txt file found in the
## top-level directory of this distribution and at:
##	 https://confluence.slac.stanford.edu/display/ppareg/LICENSE.html.
## No part of 'axi-soc-ultra-plus-core', including this file,
## may be copied, modified, propagated, or distributed except according to
## the terms contained in the LICENSE.txt file.
##############################################################################

# Unmount the kernel partition
umount /media/sd-mmcblk0p2
rm -r /media/sd-mmcblk0p2

# Kill any stale runtime applications
killall python3
sleep 5

# Remove kernel drivers in-case they are already loaded
rmmod -s axi_memory_map
rmmod -s axi_stream_dma

# Check if mac file exists in SD boot partition
if [ -f "/media/sd-mmcblk0p1/mac" ]
then
	# Set the MAC address with file
	ip link set dev eth0 down
	ip link set dev eth0 address $(cat /media/sd-mmcblk0p1/mac)
	ip link set dev eth0 up
	/etc/init.d/networking restart
# Else set the MAC from efuse values
else
	# Place holder for future support (https://jira.slac.stanford.edu/browse/ESRFOC-10)
	sleep 1
fi

# Load the user's firmware (PL) .bit file
fpgautil -b /media/sd-mmcblk0p1/system.bit

# Load custom kernel driver
insmod /lib/modules/$(uname -r)/extra/axi_memory_map.ko
insmod /lib/modules/$(uname -r)/extra/axi_stream_dma.ko

# Check if user's runtime application exists
if [ -f "/media/sd-mmcblk0p1/runtimeApp" ]
then
	# Start the user's runtime Application
	/media/sd-mmcblk0p1/runtimeApp
else
	# Start the the rogue TCP bridge Application
	/usr/bin/roguetcpbridge
fi
